# fly.toml file for formulario-asesores
app = 'formulario-asesores' # This should match your app name
primary_region = 'gru' # This should match your chosen region (Sao Paulo)

[build]
dockerfile = 'Dockerfile'

# The 'web' process for handling API requests
[[services]]
protocol = 'tcp'
internal_port = 8000
processes = ['web']

[[services.ports]]
port = 80
handlers = ['http']
[[services.ports]]
port = 443
handlers = ['tls', 'http']

# Define the commands for both your web and worker processes
[processes]
web = './start.sh deno run --allow-all src/routes/reports.ts'
worker = './start.sh deno run --allow-all src/workers/report_processor.ts'