# Netlify Build & Deploy Configuration

# [build] settings apply to the frontend Vue app
[build]
# Build command to run for the frontend
command = "npm run build"
# The directory that contains the built frontend site
publish = "dist"
